### ISSUE TITLE
Button Debounce

### ISSUE THREAD

**Issue by DrewBatchelor** [Ax-LED/volumio-pirate-audio#15]
Hi @Ax-LED,
On a Zero 2 the up and down buttons for the menus is not working correctly, we are more likely to get a double button press than a single button press, and skip menu items.
In all the other functions I tried, the debounce works fine.
Thanks 
Drew

**Comment by Ax-LED** [comment]
@DrewBatchelor 

thanks for the hint. Has nothing to do with button bouncing, but it seems that pi zero 2 has more "compute power" so it happens.
Your issue can be fixed with time.sleep(), which repository are you using?
[https://github.com/Ax-LED/volumio-plugins/tree/master/plugins/miscellanea/pirateaudio](https://github.com/Ax-LED/volumio-plugins/tree/master/plugins/miscellanea/pirateaudio)
or
[https://github.com/Ax-LED/volumio-plugins-sources/tree/master/pirateaudio](https://github.com/Ax-LED/volumio-plugins-sources/tree/master/pirateaudio)
So i can give your informations how to fix it.

AxLED

**Comment by DrewBatchelor** [comment]
Ah that's great, All the clue I needed,  added a couple of time.sleep(0.1)  to the menus and this has fixed it. I will share the details.
